---
# tasks file for kubelet
- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - kubelet

- name: Install config file
  template: 
    src: kubelet-conf.yml.j2
    dest: /etc/kubernetes/kubelet-conf.yml
  notify: Start the service

- name: Install systemd file
  template: 
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify: Start the service