---
# tasks file for kubelet
- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - kubelet

- name: Create data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /etc/kubernetes/manifests

- name: Install config file
  template: 
    src: kubelet-conf.yml.j2
    dest: /etc/kubernetes/kubelet-conf.yml

- name: Check bootstrap token
  stat: 
    path: /etc/kubernetes/bootstrap-token.yml
  register: bootstrap_token

- name: Register token id
  command: openssl rand -hex 3
  register: TOKEN_ID
  run_once: true
  when: not bootstrap_token.stat.exists

- name: Register token secret
  command: openssl rand -hex 8
  register: TOKEN_SECRET
  run_once: true
  when: not bootstrap_token.stat.exists

- name: Create bootstrap token --- part.1
  template: 
    src: bootstrap-token.yml.j2
    dest: /etc/kubernetes/bootstrap-token.yml
  when: not bootstrap_token.stat.exists

- name: Create bootstrap token --- part.2
  command: kubectl apply -f /etc/kubernetes/bootstrap-token.yml
  when: not bootstrap_token.stat.exists


- name: Check bootstrap kubeconfig
  stat: 
    path: /etc/kubernetes/bootstrap.kubeconfig
  register: bootstrap_kubeconfig

- name: Create kubeconfig
  shell: |
    kubectl config set-cluster {{ kubernetes.name }} \
      --certificate-authority=/etc/kubernetes/pki/ca.crt \
      --embed-certs=true \
      --server=https://{{ ansible_default_ipv4.address }}:6443 \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }} && \
    kubectl config set-context {{ item.KUBE_USER }}@{{ kubernetes.name }} \
      --cluster={{ kubernetes.name }} \
      --user={{ item.KUBE_USER }} \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }} && \
    kubectl config set-credentials {{ item.KUBE_USER }} \
      --token=${BOOTSTRAP_TOKEN} \
      --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }} && \
    kubectl config use-context {{ item.KUBE_USER }}@{{ kubernetes.name }} --kubeconfig=/etc/kubernetes/{{ item.KUBE_CONFIG }}
  with_items:
    - { KUBE_USER: 'kubelet-bootstrap', KUBE_CONFIG: 'bootstrap.kubeconfig' }
  when: not bootstrap_kubeconfig.stat.exists

- name: Approve kubeadm:kubelet-bootstrap
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: kubeadm:kubelet-bootstrap
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:node-bootstrapper
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:bootstrappers

- name: Approve all CSRs for the group "system:bootstrappers"
  k8s:
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: auto-approve-csrs-for-group
      subjects:
      - kind: Group
        name: system:bootstrappers
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: system:certificates.k8s.io:certificatesigningrequests:nodeclient
        apiGroup: rbac.authorization.k8s.io

- name: Approve renewal CSRs for the group "system:nodes"
  k8s:
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: auto-approve-renewals-for-nodes
      subjects:
      - kind: Group
        name: system:nodes
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: system:certificates.k8s.io:certificatesigningrequests:selfnodeclient
        apiGroup: rbac.authorization.k8s.io

- name: Install systemd file
  template: 
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service