---
# tasks file for ca
- name: Create certificate directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
  - '{{ ca.kubernetes.location }}'
  - '{{ ca.etcd.location }}'

- name: Create openssl template
  template: 
    src: openssl.cnf.j2
    dest: '{{ ca.kubernetes.location }}/openssl.cnf'