---
# tasks file for etcd
- name: Install the Etcd binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - etcd
    - etcdctl