---
# tasks file for etcd
- name: Install the Etcd binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - etcd
    - etcdctl

- name: Create data directory
  file: 
    name: '{{ kubernetes.etcd.datadir }}'
    state: directory
    mode: '0755'

- name: Create certificate directory
  file: 
    name: '{{ ca.etcd.location }}'
    state: directory
    mode: '0755'

- name: Distribution of certificate
  copy: 
    src: '{{ ca.etcd.location }}/{{ item }}'
    dest: '{{ ca.etcd.location }}'
    owner: root
    group: root
  with_items:
    - ca.crt
    - server.crt
    - server.key
    - peer.crt
    - peer.key

- name: Install systemd file
  template: 
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Start the service
  systemd:
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Wait for Etcd
  wait_for:
    port: 2379
    delay: 15
    state: started
    host: '{{ ansible_ssh_host }}'

- name: Health check
  command: ETCDCTL_API=3 /usr/local/bin/etcdctl --endpoints {{ ansible_default_ipv4.address }}:2379 --cacert {{ ca.etcd.location }}/ca.crt --cert {{ ca.etcd.location }}/server.crt --key {{ ca.etcd.location }}/server.key endpoint health