---
# tasks file for kube-apiserver
- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - kube-apiserver
  notify: Start the service

- name: Install systemd file
  template: 
    src: kube-apiserver.j2
    dest: /etc/systemd/system/kube-apiserver
  notify: Start the service