---
# tasks file for docker
- name: Install the binary
  copy: 
    src: '{{ item }}'
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  with_items:
    - containerd
    - containerd-shim
    - ctr
    - docker
    - dockerd
    - docker-init
    - docker-proxy
    - runc

- name: Create data directory
  file: 
    name: '{{ kubernetes.docker.datadir }}'
    state: directory
    mode: '0755'

- name: Install systemd file
  template: 
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service