- name: Clean kubeconfig for kube-minion nodes
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - ~/.kube
    - /etc/kubernetes/admin.kubeconfig
    - '{{ca.kubernetes.location }}/admin.crt'
    - '{{ca.kubernetes.location }}/admin.key'
  when: inventory_hostname in groups['worker']