---
# tasks file for addon
- name: Create data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ kubernetes.addon.location }}'
  when: inventory_hostname in groups['master']

- name: Master not scheduling
  shell: |
    {% if nodename is defined %}
      kubectl taint node {{ nodename }} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% else %}
      kubectl taint node {{ hostvars[inventory_hostname].hostname }} node-role.kubernetes.io/master="":NoSchedule --overwrite
    {% endif %}
  when: 
    - not kubernetes.settings.master_run_pod | default(false) | bool
    - inventory_hostname in groups['master']

- name: Update node roles
  shell: |
    {% if nodename is defined %}
      kubectl label node {{ nodename }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% else %}
      kubectl label node {{ hostvars[inventory_hostname].hostname }} {% if inventory_hostname in groups['master'] %} node-role.kubernetes.io/master=""{% else %} node-role.kubernetes.io/worker=""{% endif %} --overwrite
    {% endif %}

- name: Kubernetes Addon CoreDNS
  include_tasks: coredns.yml

- name: Kubernetes Addon Flannel
  include_tasks: flannel.yml
  when: kubernetes.network == "flannel"

- name: Kubernetes Addon Canal
  include_tasks: canal.yml
  when: kubernetes.network == "canal"

- name: Kubernetes Addon Calico
  include_tasks: calico.yml
  when: kubernetes.network == "calico"

- name: Kubernetes Done
  include_tasks: clean.yml